# Generated by Django 5.1.7 on 2025-04-22 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IBAN', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('monedas', models.CharField(choices=[('EUR', 'Euros'), ('Dollar', 'DOL'), ('Libras', 'LIB')], default='EUR', max_length=50)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('vendedor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.vendedor')),
            ],
        ),
    ]
