# Generated by Django 5.1.7 on 2025-04-10 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_tienda_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IBAN', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('monedas', models.CharField(choices=[('EUR', 'Euros'), ('Dollar', 'DOL'), ('LIB', 'Libras')], default='EUR', max_length=50)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente')),
            ],
        ),
    ]
