# Generated by Django 5.1.7 on 2025-04-24 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_precio_cuentabancaria_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='monedas',
            field=models.CharField(choices=[('Euros', 'EUR'), ('DOL', 'Dollar'), ('Libras', 'LIB')], default='EUR', max_length=50),
        ),
        migrations.CreateModel(
            name='DatosVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('facturacion', models.CharField(max_length=50)),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda.vendedor')),
            ],
        ),
    ]
