# Generated by Django 5.1.7 on 2025-04-24 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_cuentabancaria_monedas_datosvendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='monedas',
            field=models.CharField(choices=[('Euros', 'EUR'), ('Dollar', 'DOL'), ('LIB', 'Libras')], default='EUR', max_length=50),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tienda')),
            ],
        ),
        migrations.AddField(
            model_name='tienda',
            name='producto',
            field=models.ManyToManyField(through='tienda.Inventario', to='tienda.producto'),
        ),
    ]
