# Generated by Django 5.1.7 on 2025-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_cuentabancaria_monedas_inventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='monedas',
            field=models.CharField(choices=[('EUR', 'Euros'), ('DOL', 'Dollar'), ('LIB', 'Libras')], default='EUR', max_length=50),
        ),
    ]
